---
- name: GLOBAL => create main directory
  ansible.builtin.file:
    path: "{{ main_folder }}"
    state: directory
    mode: '0755'
- name: GLOBAL => create systemd directory
  ansible.builtin.file:
    path: "{{ main_folder }}/systemd"
    state: directory
    mode: '0755'
- name: GLOBAL => login to registry.redhat.io
  containers.podman.podman_login:
    username: "{{rhn-user}}"
    password: "{{rhn-pass}}"
    registry: registry.redhat.io
